// SPDX-License-Identifier: AGPL-3.0-only
// Generated by tools/letters/pack.mjs from tools/letters/sets.json and the CC0 scans -- do not edit by hand.
// Draw's factory letter sets: ornamental capitals traced from the British Library's book images (CC0; the books
// and pages are draw/vendor-notices/british-library-letters-CC0.txt). No set rides in the page: each is its own file,
// draw/letters/<id>.json (the public plug-ins repository's letters/<id>.json), which the page holds once the plug-in
// door has brought it (draw/draw.js) and which this module admits. A set is one self-describing shape: {id, name, em,
// bearing, space, source, books, glyphs}, each glyph [advance, path] -- the path one even-odd outline in the em (the
// capital's height is the em, x from the ink's left edge), the advance its ink width and the set's two bearings.
const LETTER_PATH = /^(?:M\d+ \d+(?:[lc]-?\d+(?: -?\d+|-\d+)*)*z)+$/, LETTER_ID = /^[a-z][a-z0-9-]{0,31}$/, CAPITALS = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ';
export const LETTER_LIMITS = Object.freeze({ glyph: 8000, set: 160000 });

// A set from its shape (an object, JSON text or its UTF-8 bytes); null when anything in it is not a set.
export function admitLetterSet(raw) {
	try {
		if (raw instanceof Uint8Array || raw instanceof ArrayBuffer) raw = new TextDecoder('utf-8', { fatal: true }).decode(raw);
		if (typeof raw === 'string') { if (raw.length > LETTER_LIMITS.set + 8192) return null; raw = JSON.parse(raw); }
	} catch (_) { return null; }
	if (!raw || typeof raw !== 'object' || !LETTER_ID.test(raw.id) || typeof raw.name !== 'string' || !/^[\p{L}\p{N} ]{1,24}$/u.test(raw.name)) return null;
	const whole = (n, min, max) => Number.isInteger(n) && n >= min && n <= max;
	if (raw.em !== 1000 || !whole(raw.bearing, 0, 200) || !whole(raw.space, 100, 1000) || !raw.glyphs || typeof raw.glyphs !== 'object') return null;
	const glyphs = {};
	let bytes = 0;
	for (const [letter, glyph] of Object.entries(raw.glyphs)) {
		if (!/^[A-Z]$/.test(letter) || !Array.isArray(glyph) || !whole(glyph[0], 2 * raw.bearing + 1, 4000) || typeof glyph[1] !== 'string' || glyph[1].length > LETTER_LIMITS.glyph || !LETTER_PATH.test(glyph[1])) return null;
		bytes += glyph[1].length;
		glyphs[letter] = Object.freeze([glyph[0], glyph[1]]);
	}
	if (Object.keys(glyphs).length !== 26 || bytes > LETTER_LIMITS.set) return null;
	const text = value => typeof value === 'string' && value.length <= 400 ? value : '';
	return Object.freeze({ id: raw.id, name: raw.name, em: 1000, bearing: raw.bearing, space: raw.space, source: text(raw.source), books: Array.isArray(raw.books) ? Object.freeze(raw.books.map(text).filter(Boolean)) : Object.freeze([]), glyphs: Object.freeze(glyphs) });
}

// The glyph a character takes in a set: A-Z, and a-z as its capital; anything else is not the set's. [advance, path],
// the path null for a capital the page has the advance of and not the outline (drawn in the serif, held to the advance).
export function letterGlyph(set, character) {
	return set && /^[A-Za-z]$/.test(character) ? set.glyphs[character.toUpperCase()] : null;
}

// The sets Rapier offers: each set's name and metrics (its bearing, its space and the advances of A to Z) and the pin of
// its file draw/letters/<id>.json, the length and SHA-384 (base64) the plug-in loader holds its bytes to.
const CATALOGUE = [{"id":"field","name":"Field","bearing":30,"space":300,"advances":[1046,1045,1047,1058,1050,1017,1060,1026,1040,1071,1061,1056,1062,1079,1074,1032,1057,1052,1035,1026,1048,1062,1034,1061,1048,1042],"bytes":96902,"sha384":"VFsCE/7zS6Kkq/EW1/7NfYHVGoVXNUm0pWHdtJmzXwhWgJWBSKhNHuU0ODuGCar0"},{"id":"relief","name":"Relief","bearing":20,"space":300,"advances":[1165,1025,1046,1068,1058,1065,1094,1163,775,1086,1067,1073,1375,1135,1021,1011,885,1117,936,1151,1064,1131,1460,1015,1025,1041],"bytes":95172,"sha384":"tQctBake2gu7B/v5/1jC6XFt5smV5uVg7W7GdJXsJZBZ62Zc7crSP3zRkZPgQqgq"},{"id":"leaf","name":"Leaf","bearing":20,"space":300,"advances":[1049,1043,1058,1025,1032,1039,1039,1036,1055,1040,1042,1073,1032,1055,1058,1027,1031,1027,1043,1047,1033,1036,1036,1106,1064,999],"bytes":134918,"sha384":"DtSKWtWhiitlNOfjx9o5Jf0FYcpWLw4nmWAjo1eAA3FOvs2OjB2hddHlRCnrtZ7g"},{"id":"arabesque","name":"Arabesque","bearing":20,"space":300,"advances":[1033,1035,1030,1038,1042,1029,1044,1026,1019,1032,908,1033,1044,1057,1060,1030,1038,1025,1033,1078,1056,1039,1055,1040,902,1046],"bytes":136035,"sha384":"Zx2z2bEpD4VNkIccLejcUY68eqAFraPEN7hqsqkcVqHOKGvsSMqbLLiXXklvZINl"}];
export const LETTER_SETS = Object.freeze(CATALOGUE.map(entry => Object.freeze({ ...entry, advances: Object.freeze(entry.advances) })));
const HELD = new Map(), KEPT = new Map(), SHOWN = new Map();

// A set that arrived as its file's bytes (verified against its pin by the plug-in door): admitted and held for this page
// when the catalogue offers it. The set, or null.
export function holdLetterSet(raw) {
	const set = admitLetterSet(raw);
	if (!set || !LETTER_SETS.some(entry => entry.id === set.id)) return null;
	HELD.set(set.id, set); SHOWN.delete(set.id);
	return set;
}
export function letterSetHeld(id) { return HELD.has(id); }

// A capital a drawing's own SVG carries (draw/text.mjs restoreLetters), kept for a set this page does not hold; the first
// kept for a letter stays.
export function keepLetterGlyph(id, letter, path) {
	if (HELD.has(id) || !LETTER_SETS.some(entry => entry.id === id) || letter.length !== 1 || !CAPITALS.includes(letter) || typeof path !== 'string' || path.length > LETTER_LIMITS.glyph || !LETTER_PATH.test(path)) return false;
	if (!KEPT.has(id)) KEPT.set(id, new Map());
	if (!KEPT.get(id).has(letter)) { KEPT.get(id).set(letter, path); SHOWN.delete(id); }
	return true;
}

// The set a text in `letters:<id>` is drawn with: the whole set once held; before that the catalogue's metrics with the
// capitals kept from drawings, every other capital measured by its advance and drawn in the serif; null for an id no set has.
export function letterSet(id) {
	if (HELD.has(id)) return HELD.get(id);
	if (SHOWN.has(id)) return SHOWN.get(id);
	const entry = LETTER_SETS.find(item => item.id === id);
	if (!entry) return null;
	const kept = KEPT.get(id), shown = Object.freeze({ id, name: entry.name, em: 1000, bearing: entry.bearing, space: entry.space,
		glyphs: Object.freeze(Object.fromEntries([...CAPITALS].map((c, i) => [c, Object.freeze([entry.advances[i], kept?.get(c) || null])]))) });
	SHOWN.set(id, shown);
	return shown;
}
